language: node_js
node_js:
  - "0.10"

before_install:
  - "export NODE_ENV=test"

branches:
  only:
    - master

script:
  - npm test

notifications:
  email:
    on_success: change
    on_failure: always
