language: node_js
node_js:
  - "0.10"

before_install:
  - "export NODE_ENV=test"

branches:
  only:
    - master

script:
  - npm test
  - ./node_modules/.bin/istanbul cover --root backend ./node_modules/.bin/_mocha --report lcovonly -- backend/test/* && cat ./coverage/lcov.info | bin/coveralls && rm -rf ./coverage

notifications:
  email:
    on_success: change
    on_failure: always
